name=BQ27427 Battery Fuel Gauge Micropython Library
version=1.0.0
author=KIP
maintainer=KIP
sentence=Micropython port of Edrean Ernst's Arduino library for interfacing with the BQ27427 LiPo Fuel Gauge
paragraph=Micropython port of Edrean Ernst's Arduino library for interfacing with the BQ27427 LiPo Fuel Gauge
category=Sensors
url=https://github.com/KipJM/BQ27427_micropython
architectures=*
